#!/usr/bin/env python3
"""Refresh/check pinned Python dependencies for HADES backend (Linux + Windows).

Generates ``backend/requirements.lock.txt`` from the active backend virtualenv
after installing ``backend/requirements.txt``. The lock is a ``pip freeze`` snapshot
validated against direct requirement names — not an invented graph.

Usage:
  python scripts/refresh_python_constraints.py
  python scripts/refresh_python_constraints.py --check
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS = ROOT / "backend" / "requirements.txt"
LOCK_PATH = ROOT / "backend" / "requirements.lock.txt"
VENV_PYTHON = ROOT / "backend" / ".venv" / "Scripts" / "python.exe"
if not VENV_PYTHON.is_file():
    VENV_PYTHON = ROOT / "backend" / ".venv" / "bin" / "python"


def _parse_requirement_names(path: Path) -> set[str]:
    names: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or line.startswith("-"):
            continue
        token = re.split(r"[<>=!~\[]", line, maxsplit=1)[0].strip()
        if token:
            names.add(token.lower().replace("-", "_"))
    return names


def _normalize_name(name: str) -> str:
    return name.lower().replace("-", "_")


def _pip_freeze() -> list[str]:
    if not VENV_PYTHON.is_file():
        raise SystemExit(f"backend venv python not found: {VENV_PYTHON}")
    proc = subprocess.run(
        [str(VENV_PYTHON), "-m", "pip", "freeze"],
        check=True,
        capture_output=True,
        text=True,
    )
    return [line.strip() for line in proc.stdout.splitlines() if line.strip()]


def build_lock_lines() -> list[str]:
    if not REQUIREMENTS.is_file():
        raise SystemExit(f"missing {REQUIREMENTS}")
    direct = _parse_requirement_names(REQUIREMENTS)
    freeze = _pip_freeze()
    selected: list[str] = []
    for line in freeze:
        pkg = _normalize_name(line.split("==", 1)[0])
        if pkg in direct:
            selected.append(line)
    if len(selected) < len(direct):
        missing = sorted(direct - {_normalize_name(l.split("==", 1)[0]) for l in selected})
        raise SystemExit(
            "Lock generation failed: direct requirements missing from venv freeze: "
            + ", ".join(missing)
            + ". Install backend/requirements.txt in the venv first."
        )
    header = [
        "# Generated by scripts/refresh_python_constraints.py — do not hand-edit.",
        "# Recreate: python scripts/refresh_python_constraints.py",
        f"# Source: {REQUIREMENTS.relative_to(ROOT).as_posix()}",
        "",
    ]
    return header + sorted(selected, key=str.lower) + [""]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit non-zero if lock file is stale")
    args = parser.parse_args()
    expected = "\n".join(build_lock_lines())
    if args.check:
        if not LOCK_PATH.is_file():
            print(f"Missing lock file: {LOCK_PATH}", file=sys.stderr)
            return 1
        current = LOCK_PATH.read_text(encoding="utf-8")
        if current != expected:
            print("backend/requirements.lock.txt is out of date; run refresh_python_constraints.py", file=sys.stderr)
            return 1
        return 0
    LOCK_PATH.write_text(expected, encoding="utf-8")
    print(f"Wrote {LOCK_PATH.relative_to(ROOT)} ({len(expected.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
