import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), "utf8");

test("FINALBETA settings page matches Instellingen reference layout + live wiring", async () => {
  const page = await read("components/hades/finalbeta/pages/finalbeta-settings-page.tsx");
  const css = await read("components/hades/styles/finalbeta/v2/settings.css");
  const mocks = await read("components/hades/finalbeta/mocks/settings.ts");

  assert.match(page, /settings-page/);
  assert.match(page, /data-live="settings"/);
  assert.match(page, /useHadesSettings/);
  assert.match(page, /Configure today\. Amplify tomorrow/);
  assert.match(page, /Systeemvoorkeuren, interface, policies en beheer van HADES/);
  assert.match(page, /Algemene instellingen/);
  assert.match(page, /Interface thema & density/);
  assert.match(page, /Notificaties/);
  assert.match(page, /Privacy & beveiliging/);
  assert.match(page, /Lokale runtime voorkeuren/);
  assert.match(page, /AI policies/);
  assert.match(page, /Autosave & updates/);
  assert.match(page, /Keyboard shortcuts/);
  assert.match(page, /Integraties/);
  assert.match(page, /Same control\. More possibilities/);
  assert.match(page, /HADES Core/);
  assert.match(page, /Beveiliging/);
  assert.match(page, /Snelle acties/);
  assert.match(page, /Build a smarter tomorrow/);
  assert.match(page, /appClassName="settings-app"/);
  assert.match(page, /mainClassName="settings-main"/);
  assert.match(page, /export function FinalBetaSettingsPage/);
  assert.match(page, /pageId/);
  assert.match(page, /onNavigate/);
  assert.match(page, /useUiStyle/);
  assert.match(page, /settings\.patch/);
  assert.match(page, /file_write_policy/);
  assert.match(page, /network_policy/);
  assert.match(page, /plugin_autonomous_tools/);
  assert.match(page, /max_tool_rounds/);
  assert.match(page, /applyStyle\("lux"\)/);
  assert.match(page, /applyStyle\("finalbeta"\)/);
  assert.match(page, /HADES Lux/);
  assert.match(page, /FINALBETA/);
  assert.match(page, /uiStyle === "finalbeta"/);
  assert.match(page, /SETTINGS_RUNTIME_SLIDERS/);
  assert.match(page, /set-slider/);
  assert.match(css, /\.fb-root \.settings-page/);
  assert.match(css, /\.fb-root \.settings-grid/);
  assert.match(css, /\.fb-root \.set-card/);
  assert.match(css, /\.fb-root \.set-toggle\.on/);
  assert.match(css, /\.fb-root \.set-theme\.active/);
  assert.match(css, /\.fb-root \.set-slider/);
  assert.match(css, /\.fb-root \.set-chip/);
  assert.match(mocks, /HADES Dark/);
  assert.match(mocks, /VRAM limiet/);
  assert.match(mocks, /75%/);
});
