"""Autogenerated pool entrypoint — agents."""
from __future__ import annotations

from Data.modules.workers.entrypoints._cli import main_for_pool


def main(argv=None):
    return main_for_pool("agents", handler=None, argv=argv)

if __name__ == "__main__":
    raise SystemExit(main())
