"""Autogenerated pool entrypoint — coding."""
from __future__ import annotations

from Data.modules.workers.entrypoints._cli import main_for_pool

def _handler(ctx, job):
    from Data.modules.jobs.states import JobState
    # Domain coding worker advances one coding.advance job
    from Data.modules.coding.worker import CodingWorker
    # Minimal: mark that coding pool claimed; prefer existing process via scripts path
    args = dict(job.arguments or {})
    session_id = str(args.get("session_id") or "")
    if not session_id:
        ctx["job_store"].transition(job.job_id, JobState.FAILED, error="missing session_id")
        return {}
    # Leave execution to CodingWorker when bound; here use gateway-less domain import carefully
    try:
        from Data.modules.coding.service import CodingControlPlane
        # Cannot construct full plane without settings wiring — use job_runtime path
        runtime = ctx["job_runtime"]
        # Re-queue is wrong; execute via store metadata for coding worker scripts
        # Mark RUNNING job arguments for external coding loop in same process:
        from Data.backend.config import load_settings
        settings = load_settings()
        plane = CodingControlPlane.from_settings(settings, job_runtime=runtime)
        plane.worker.process_next()
    except Exception as exc:
        refreshed = ctx["job_store"].get(job.job_id)
        if refreshed and refreshed.state.value == "RUNNING":
            ctx["job_store"].transition(job.job_id, JobState.FAILED, error=str(exc))
    return {}


def main(argv=None):
    return main_for_pool("coding", handler=_handler, argv=argv)

if __name__ == "__main__":
    raise SystemExit(main())
