"""Autogenerated pool entrypoint — knowledge_commit."""
from __future__ import annotations

from Data.modules.workers.entrypoints._cli import main_for_pool

def _handler(ctx, job):
    from Data.modules.jobs.states import JobState
    try:
        from Data.modules.knowledge.pipeline.committer import KnowledgeCommitter
        committer = KnowledgeCommitter.from_env(ctx)
        receipt = committer.commit_job(job)
        store = ctx["job_store"]
        store.transition(job.job_id, JobState.COMPLETED, result=receipt if isinstance(receipt, dict) else {"ok": True})
    except Exception as exc:
        ctx["job_store"].transition(job.job_id, JobState.FAILED, error=str(exc))
    return {}


def main(argv=None):
    return main_for_pool("knowledge_commit", handler=_handler, argv=argv)

if __name__ == "__main__":
    raise SystemExit(main())
