"""Autogenerated pool entrypoint — maintenance."""
from __future__ import annotations

from Data.modules.workers.entrypoints._cli import main_for_pool

def _handler(ctx, job):
    from Data.modules.jobs.leases import fenced_transition
    from Data.modules.jobs.states import JobState
    store = ctx["job_store"]
    worker_id = str(ctx.get("worker_id") or "")
    recovered = 0
    if hasattr(store, "recover_expired_leases"):
        recovered = len(store.recover_expired_leases())
    elif hasattr(store, "list_expired_leases"):
        for expired in store.list_expired_leases():
            try:
                if hasattr(store, "schedule_retry"):
                    store.schedule_retry(expired.job_id, delay_seconds=1.0, error="lease_expired")
                else:
                    store.transition(expired.job_id, JobState.QUEUED, error="lease_expired_recovery")
                recovered += 1
            except Exception:
                pass
    ctx["admission"].recover_expired()
    ctx["registry"].reconcile_stale(heartbeat_ttl_seconds=60.0)
    fenced_transition(
        store,
        job.job_id,
        JobState.COMPLETED,
        worker_id=worker_id,
        ctx=ctx,
        result={"recovered": recovered},
    )
    return {"recovered": recovered}


def main(argv=None):
    return main_for_pool("maintenance", handler=_handler, argv=argv)

if __name__ == "__main__":
    raise SystemExit(main())
