"""Autogenerated pool entrypoint — market_sim."""
from __future__ import annotations

from Data.modules.workers.entrypoints._cli import main_for_pool

def _handler(ctx, job):
    from Data.modules.jobs.states import JobState
    try:
        from Data.modules.market_sim.worker import build_worker_from_env
        worker = build_worker_from_env()
        if hasattr(worker, "process_next"):
            worker.process_next()
        ctx["job_store"].transition(job.job_id, JobState.COMPLETED, result={"market_sim": True})
    except Exception as exc:
        ctx["job_store"].transition(job.job_id, JobState.FAILED, error=str(exc))
    return {}


def main(argv=None):
    return main_for_pool("market_sim", handler=_handler, argv=argv)

if __name__ == "__main__":
    raise SystemExit(main())
