"""Autogenerated pool entrypoint — rerank (specialist inference)."""
from __future__ import annotations

from Data.modules.workers.entrypoints._cli import main_for_pool


def _handler(ctx, job):
    from Data.modules.rerank.worker import process_rerank_job

    return process_rerank_job(ctx, job)


def main(argv=None):
    return main_for_pool("rerank", handler=_handler, argv=argv)


if __name__ == "__main__":
    raise SystemExit(main())
