"""Autogenerated pool entrypoint — research."""
from __future__ import annotations

from Data.modules.workers.entrypoints._cli import main_for_pool

def _handler(ctx, job):
    from Data.modules.jobs.states import JobState
    args = dict(job.arguments or {})
    action = str(args.get("action") or "advance")
    project_id = str(args.get("project_id") or "")
    # Durable research continuation — domain service methods
    try:
        from Data.modules.research.worker import process_research_job
        result = process_research_job(ctx, job)
        if result is None:
            ctx["job_store"].transition(job.job_id, JobState.COMPLETED, result={"action": action, "project_id": project_id})
        return result or {}
    except ImportError:
        ctx["job_store"].transition(
            job.job_id,
            JobState.COMPLETED,
            result={"action": action, "project_id": project_id, "deferred_domain": True},
        )
        return {}


def main(argv=None):
    return main_for_pool("research", handler=_handler, argv=argv)

if __name__ == "__main__":
    raise SystemExit(main())
