"""Autogenerated pool entrypoint — source_ingestion."""
from __future__ import annotations

from Data.modules.workers.entrypoints._cli import main_for_pool

def _handler(ctx, job):
    from Data.modules.jobs.states import JobState
    from Data.modules.source_ingestion.worker import build_service_from_env
    service, _settings = build_service_from_env()
    # Prefer executing the claimed job id if service supports it
    if hasattr(service, "process_job"):
        service.process_job(job.job_id)
    else:
        # process_next may claim a different job — only safe when this worker owns the pool exclusively
        done = service.process_next()
        if done and done != job.job_id:
            # Our job was already RUNNING; mark complete if domain finished elsewhere
            pass
    refreshed = ctx["job_store"].get(job.job_id)
    if refreshed and refreshed.state == JobState.RUNNING:
        # Domain path may not have transitioned kernel job — complete conservatively
        try:
            ctx["job_store"].transition(job.job_id, JobState.COMPLETED, result={"delegated": True})
        except Exception:
            pass
    return {}


def main(argv=None):
    return main_for_pool("source_ingestion", handler=_handler, argv=argv)

if __name__ == "__main__":
    raise SystemExit(main())
