"""Autogenerated pool entrypoint — source_ingestion.

Production owner: Worker Fabric ``source_ingestion`` pool.
One SourceIngestionService instance per worker process — never rebuild per job.
"""
from __future__ import annotations

from typing import Any

from Data.modules.workers.entrypoints._cli import main_for_pool

_SERVICE: Any | None = None
_SETTINGS: Any | None = None


def _get_service():
    """Process-scoped SourceIngestionService (lazy once)."""
    global _SERVICE, _SETTINGS
    if _SERVICE is None:
        from Data.modules.source_ingestion.worker import build_service_from_env

        _SERVICE, _SETTINGS = build_service_from_env()
    return _SERVICE


def _handler(ctx, job):
    from Data.modules.jobs.leases import fenced_transition
    from Data.modules.jobs.states import JobState

    service = _get_service()
    # Execute the already-claimed fabric job — do not re-claim via process_next.
    if hasattr(service, "process_job"):
        service.process_job(
            job.job_id,
            worker_id=str(ctx.get("worker_id") or ""),
            already_claimed=True,
            job=job,
        )
    else:
        # Fail closed rather than claiming a different job.
        raise RuntimeError(
            "SOURCE_INGESTION_PROCESS_JOB_REQUIRED: fabric worker cannot use process_next"
        )
    refreshed = ctx["job_store"].get(job.job_id)
    if refreshed and refreshed.state == JobState.RUNNING:
        # Domain path may not have transitioned kernel job — complete conservatively
        try:
            fenced_transition(
                ctx["job_store"],
                job.job_id,
                JobState.COMPLETED,
                result={"delegated": True},
                worker_id=str(ctx.get("worker_id") or ""),
                ctx=ctx,
            )
        except Exception:
            pass
    return {}


def main(argv=None):
    return main_for_pool("source_ingestion", handler=_handler, argv=argv)


if __name__ == "__main__":
    raise SystemExit(main())
