"""Autogenerated pool entrypoint — training_control."""
from __future__ import annotations

from Data.modules.workers.entrypoints._cli import main_for_pool


def main(argv=None):
    return main_for_pool("training_control", handler=None, argv=argv)

if __name__ == "__main__":
    raise SystemExit(main())
