"""Structured ATME / training failure codes."""

from __future__ import annotations

from enum import StrEnum


class TrainingFailureCode(StrEnum):
    UNSUPPORTED_ARCHITECTURE = "UNSUPPORTED_ARCHITECTURE"
    INSUFFICIENT_VRAM = "INSUFFICIENT_VRAM"
    INSUFFICIENT_RAM = "INSUFFICIENT_RAM"
    INSUFFICIENT_STORAGE = "INSUFFICIENT_STORAGE"
    CUDA_RUNTIME_MISMATCH = "CUDA_RUNTIME_MISMATCH"
    BITSANDBYTES_UNAVAILABLE = "BITSANDBYTES_UNAVAILABLE"
    PINNED_MEMORY_ALLOCATION_FAILED = "PINNED_MEMORY_ALLOCATION_FAILED"
    MODEL_SHARD_MISSING = "MODEL_SHARD_MISSING"
    STREAM_READ_FAILED = "STREAM_READ_FAILED"
    CUDA_TRANSFER_FAILED = "CUDA_TRANSFER_FAILED"
    CUDA_OOM = "CUDA_OOM"
    NUMERICAL_DIVERGENCE = "NUMERICAL_DIVERGENCE"
    CANCELLED_BY_USER = "CANCELLED_BY_USER"
    LOW_CONFIDENCE_PLAN = "LOW_CONFIDENCE_PLAN"
    STRATEGY_REJECTED = "STRATEGY_REJECTED"
    PLANNER_ERROR = "PLANNER_ERROR"
    WORKER_CRASH = "WORKER_CRASH"
    DEPENDENCY_MISSING = "DEPENDENCY_MISSING"
