from __future__ import annotations

from dataclasses import dataclass
from urllib.parse import urlparse


@dataclass(frozen=True, slots=True)
class SourceSeed:
    url: str
    category: str
    priority: int = 50

    @property
    def domain(self) -> str:
        return (urlparse(self.url).hostname or "").lower().removeprefix("www.")

    @property
    def name(self) -> str:
        host = self.domain.split(":", 1)[0]
        return host


# Direct publisher / institution / company sources only. No Google News or Google Search.
# Paths are used where a site has a dedicated newsroom, research, press, or insights area.
GROUPS: dict[str, list[str]] = {
    "global_finance": [
        "https://www.reuters.com/markets/",
        "https://www.bloomberg.com/markets",
        "https://www.ft.com/",
        "https://www.wsj.com/news/business",
        "https://www.cnbc.com/",
        "https://www.marketwatch.com/",
        "https://www.barrons.com/",
        "https://www.investors.com/",
        "https://seekingalpha.com/",
        "https://www.fool.com/investing-news/",
        "https://www.benzinga.com/",
        "https://www.investing.com/news/",
        "https://finance.yahoo.com/",
        "https://www.morningstar.com/markets",
        "https://www.zacks.com/stock/news.php",
        "https://thefly.com/",
        "https://www.businessinsider.com/finance",
        "https://fortune.com/",
        "https://www.forbes.com/business/",
        "https://www.economist.com/finance-and-economics",
        "https://apnews.com/hub/business",
        "https://www.nytimes.com/section/business",
        "https://www.washingtonpost.com/business/",
        "https://www.theguardian.com/business",
        "https://www.bbc.com/business",
        "https://edition.cnn.com/business",
        "https://www.foxbusiness.com/",
        "https://www.nbcnews.com/business",
        "https://www.cbsnews.com/moneywatch/",
        "https://abcnews.go.com/Business",
        "https://www.axios.com/economy-business",
        "https://www.politico.com/news/economy",
        "https://thehill.com/business/",
        "https://www.semafor.com/business",
        "https://qz.com/",
        "https://www.fastcompany.com/",
        "https://www.inc.com/",
        "https://www.entrepreneur.com/",
        "https://www.theglobeandmail.com/business/",
        "https://financialpost.com/",
        "https://www.bnnbloomberg.ca/",
        "https://www.ctvnews.ca/business",
        "https://www.cbc.ca/news/business",
        "https://www.afr.com/",
        "https://www.smh.com.au/business",
        "https://www.theaustralian.com.au/business",
        "https://www.abc.net.au/news/business/",
        "https://www.nzherald.co.nz/business/",
        "https://www.rnz.co.nz/news/business",
        "https://www.handelsblatt.com/",
        "https://www.faz.net/aktuell/finanzen/",
        "https://www.spiegel.de/wirtschaft/",
        "https://www.welt.de/wirtschaft/",
        "https://www.lesechos.fr/",
        "https://www.lemonde.fr/economie/",
        "https://www.lefigaro.fr/economie",
        "https://www.challenges.fr/economie/",
        "https://www.expansion.com/",
        "https://elpais.com/economia/",
        "https://cincodias.elpais.com/",
        "https://www.ilsole24ore.com/",
        "https://www.milanofinanza.it/",
        "https://fd.nl/",
        "https://www.dft.nl/",
        "https://www.tijd.be/",
        "https://www.nzz.ch/wirtschaft",
        "https://www.tagesanzeiger.ch/wirtschaft",
        "https://www.wiwo.de/",
        "https://www.manager-magazin.de/",
        "https://www.business-standard.com/",
        "https://economictimes.indiatimes.com/",
        "https://www.moneycontrol.com/news/",
        "https://www.livemint.com/",
        "https://www.financialexpress.com/",
        "https://www.thehindubusinessline.com/",
        "https://www.cnbctv18.com/",
        "https://www.ndtvprofit.com/",
        "https://www.businesstoday.in/",
        "https://www.scmp.com/business",
        "https://asia.nikkei.com/",
        "https://www.japantimes.co.jp/news_category/business/",
        "https://www.koreatimes.co.kr/www/biz/",
        "https://www.koreaherald.com/business",
        "https://www.channelnewsasia.com/business",
        "https://www.straitstimes.com/business",
        "https://www.businesstimes.com.sg/",
        "https://www.theedgemalaysia.com/",
        "https://www.bworldonline.com/",
        "https://www.dawn.com/business",
        "https://tribune.com.pk/business",
        "https://www.arabnews.com/economy",
        "https://www.thenationalnews.com/business/",
        "https://gulfnews.com/business",
        "https://www.zawya.com/",
        "https://www.businessday.co.za/",
        "https://www.businessdailyafrica.com/",
        "https://www.theafricareport.com/",
    ],
    "markets_investing": [
        "https://www.thestreet.com/",
        "https://www.kiplinger.com/investing",
        "https://www.nasdaq.com/news-and-insights",
        "https://stocktwits.com/news",
        "https://www.tipranks.com/news",
        "https://www.gurufocus.com/news",
        "https://simplywall.st/news",
        "https://www.tradingview.com/news/",
        "https://www.barchart.com/story/news",
        "https://www.fxstreet.com/news",
        "https://www.forexlive.com/",
        "https://www.dailyfx.com/market-news",
        "https://www.babypips.com/news",
        "https://www.kitco.com/news",
        "https://www.mining.com/",
        "https://oilprice.com/Latest-Energy-News/World-News/",
        "https://www.rigzone.com/news/",
        "https://www.spglobal.com/marketintelligence/en/news-insights/latest-news-headlines",
        "https://www.argusmedia.com/en/news-and-insights",
        "https://www.institutionalinvestor.com/",
        "https://www.ai-cio.com/",
        "https://www.planadviser.com/",
        "https://www.wealthmanagement.com/",
        "https://www.thinkadvisor.com/",
        "https://www.investmentnews.com/",
        "https://citywire.com/",
        "https://portfolio-adviser.com/",
        "https://www.hedgeweek.com/",
        "https://www.privatedebtinvestor.com/",
        "https://www.privateequityinternational.com/",
        "https://www.infrastructureinvestor.com/",
        "https://www.pehub.com/",
        "https://www.venturecapitaljournal.com/",
        "https://pitchbook.com/news",
        "https://news.crunchbase.com/",
        "https://www.dealstreetasia.com/",
        "https://www.ionanalytics.com/insights/",
        "https://www.law360.com/",
        "https://www.globest.com/",
        "https://www.bisnow.com/",
        "https://www.costar.com/news/",
        "https://commercialobserver.com/",
        "https://propmodo.com/",
        "https://www.realestatenews.com/",
        "https://www.housingwire.com/",
        "https://www.mortgagenewsdaily.com/",
        "https://www.pionline.com/",
        "https://www.ipe.com/",
        "https://www.fnlondon.com/",
        "https://www.euromoney.com/",
        "https://www.risk.net/",
        "https://www.globalcapital.com/",
        "https://www.bondbuyer.com/",
        "https://www.americanbanker.com/",
        "https://www.bankingdive.com/",
        "https://www.paymentsdive.com/",
        "https://www.finextra.com/",
        "https://www.fintechfutures.com/",
        "https://www.pymnts.com/",
        "https://www.fintechnews.org/",
    ],
    "crypto_blockchain": [
        "https://www.coindesk.com/",
        "https://cointelegraph.com/",
        "https://decrypt.co/",
        "https://www.theblock.co/",
        "https://blockworks.co/news",
        "https://bitcoinmagazine.com/",
        "https://news.bitcoin.com/",
        "https://cryptoslate.com/",
        "https://cryptopotato.com/",
        "https://dailyhodl.com/",
        "https://beincrypto.com/",
        "https://u.today/",
        "https://ambcrypto.com/",
        "https://www.newsbtc.com/",
        "https://cryptonews.com/",
        "https://coinjournal.net/news/",
        "https://www.coinspeaker.com/",
        "https://finbold.com/",
        "https://coinpedia.org/news/",
        "https://crypto.news/",
        "https://bitcoinist.com/",
        "https://blockonomi.com/",
        "https://thedefiant.io/",
        "https://www.bankless.com/",
        "https://messari.io/report/latest",
        "https://coinmarketcap.com/academy/article/",
        "https://www.coinbase.com/blog",
        "https://blog.kraken.com/",
        "https://www.binance.com/en/blog",
        "https://www.okx.com/learn",
        "https://learn.bybit.com/",
        "https://blog.bitfinex.com/",
        "https://www.gemini.com/blog",
        "https://ripple.com/insights/",
        "https://www.circle.com/blog",
        "https://www.chainalysis.com/blog/",
        "https://a16zcrypto.com/",
        "https://www.paradigm.xyz/",
        "https://www.electriccapital.com/blog",
        "https://panteracapital.com/blockchain-letter/",
        "https://www.galaxy.com/insights/",
        "https://research.grayscale.com/",
        "https://bitwiseinvestments.com/crypto-market-insights",
        "https://coinshares.com/insights/",
        "https://insights.glassnode.com/",
        "https://cryptoquant.com/insights",
        "https://www.kaiko.com/research",
        "https://www.nansen.ai/research",
        "https://tokeninsight.com/en/research",
        "https://coinmetrics.io/insights/",
        "https://www.blockchain.com/explorer/learning-portal",
        "https://blog.bitstamp.net/",
        "https://www.bitget.com/blog",
        "https://www.ledger.com/blog",
        "https://consensys.io/blog",
    ],
    "official_macro_regulation": [
        "https://www.sec.gov/newsroom",
        "https://www.cftc.gov/PressRoom/index.htm",
        "https://www.finra.org/media-center/newsreleases",
        "https://www.federalreserve.gov/newsevents.htm",
        "https://home.treasury.gov/news",
        "https://www.justice.gov/news",
        "https://www.ftc.gov/news-events/news/press-releases",
        "https://www.commerce.gov/news",
        "https://www.bls.gov/bls/newsrels.htm",
        "https://www.bea.gov/news",
        "https://www.fdic.gov/news/",
        "https://www.occ.treas.gov/news-issuances/index-news-issuances.html",
        "https://ncua.gov/newsroom",
        "https://www.consumerfinance.gov/about-us/newsroom/",
        "https://www.ecb.europa.eu/press/html/index.en.html",
        "https://www.esma.europa.eu/press-news/esma-news",
        "https://www.eba.europa.eu/publications-and-media/press-releases",
        "https://www.eiopa.europa.eu/media/news_en",
        "https://commission.europa.eu/news-and-media_en",
        "https://www.bankofengland.co.uk/news",
        "https://www.fca.org.uk/news",
        "https://www.gov.uk/government/organisations/hm-treasury",
        "https://www.bundesbank.de/en/press",
        "https://www.bafin.de/EN/PublikationenDaten/Pressemitteilungen/pressemitteilungen_node_en.html",
        "https://www.banque-france.fr/en/press-room",
        "https://www.amf-france.org/en/news-publications/news-releases",
        "https://www.dnb.nl/en/public-information/news/",
        "https://www.afm.nl/en/sector/actueel",
        "https://www.nbb.be/en/articles",
        "https://www.fsma.be/en/news",
        "https://www.centralbank.ie/news-media/press-releases",
        "https://www.riksbank.se/en-gb/press-and-published/",
        "https://www.fi.se/en/published/press-releases/",
        "https://www.norges-bank.no/en/news-events/news-publications/",
        "https://www.finanstilsynet.no/en/news-archive/press-releases/",
        "https://www.suomenpankki.fi/en/media-and-publications/releases/",
        "https://www.finanssivalvonta.fi/en/publications-and-press-releases/",
        "https://www.bankofcanada.ca/press/",
        "https://www.osc.ca/en/news-events/news",
        "https://www.rba.gov.au/media-releases/",
        "https://asic.gov.au/about-asic/news-centre/find-a-media-release/",
        "https://www.apra.gov.au/news-and-publications",
        "https://treasury.gov.au/news-and-media",
        "https://www.rbnz.govt.nz/hub/news",
        "https://www.fma.govt.nz/news/",
        "https://www.boj.or.jp/en/announcements/index.htm",
        "https://www.fsa.go.jp/en/news/index.html",
        "https://www.mof.go.jp/english/policy/index.htm",
        "https://www.pbc.gov.cn/en/3688110/index.html",
        "https://www.csrc.gov.cn/csrc_en/c102030/common_list.shtml",
        "https://www.safe.gov.cn/en/News/index.html",
        "https://www.hkma.gov.hk/eng/news-and-media/",
        "https://www.sfc.hk/en/News-and-announcements/News",
        "https://www.mas.gov.sg/news",
        "https://www.rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx",
        "https://www.sebi.gov.in/sebiweb/home/HomeAction.do?doListing=yes&sid=6&ssid=25&smid=0",
        "https://www.snb.ch/en/publications/communication/press-releases-restricted",
        "https://www.finma.ch/en/news/",
        "https://www.bis.org/press/",
        "https://www.imf.org/en/News",
        "https://www.worldbank.org/en/news",
        "https://www.oecd.org/newsroom/",
        "https://www.wto.org/english/news_e/news_e.htm",
        "https://www.iosco.org/news/",
        "https://www.fsb.org/news/",
        "https://www.fatf-gafi.org/en/the-fatf/news.html",
    ],
    "exchanges_market_infra": [
        "https://www.nyse.com/market-data/insights",
        "https://www.cboe.com/insights/",
        "https://www.cmegroup.com/media-room.html",
        "https://www.ice.com/insights",
        "https://www.lseg.com/en/insights",
        "https://www.londonstockexchange.com/news",
        "https://www.euronext.com/en/news",
        "https://www.deutsche-boerse.com/dbg-en/media/press-releases",
        "https://www.boerse-frankfurt.de/news",
        "https://www.six-group.com/en/newsroom.html",
        "https://www.bolsasymercados.es/ing/Studies-Research/News",
        "https://www.borsaitaliana.it/borsaitaliana/ufficio-stampa/comunicati-stampa/comunicatistampa.en.htm",
        "https://www.jpx.co.jp/english/corporate/news/news-releases/index.html",
        "https://www.hkex.com.hk/News/News-Release",
        "https://www.sgx.com/media-centre",
        "https://www.asx.com.au/about/media-releases",
        "https://www.nseindia.com/resources/exchange-communication-press-releases",
        "https://www.bseindia.com/markets/MarketInfo/DispNewNoticesCirculars.aspx?page=20240101-1",
        "https://www.tmx.com/newsroom",
        "https://www.bmv.com.mx/en/media-room",
        "https://www.b3.com.br/en_us/news/",
        "https://www.jse.co.za/news",
        "https://www.saudiexchange.sa/wps/portal/saudiexchange/newsandreports/issuer-news",
        "https://www.dfm.ae/media-center/news",
        "https://www.adx.ae/English/Pages/News.aspx",
        "https://www.boursakuwait.com.kw/news/",
        "https://global.krx.co.kr/contents/GLB/05/0501/0501000000/GLB0501000000.jsp",
        "https://www.twse.com.tw/en/about/news/news.html",
        "https://www.idx.co.id/en/news/press-release",
        "https://www.set.or.th/en/about/mediacenter/news-release",
    ],
    "sector_trade": [
        "https://techcrunch.com/",
        "https://www.theverge.com/",
        "https://arstechnica.com/",
        "https://www.wired.com/",
        "https://venturebeat.com/",
        "https://siliconangle.com/",
        "https://www.theregister.com/",
        "https://www.zdnet.com/",
        "https://www.cnet.com/tech/",
        "https://www.tomshardware.com/",
        "https://www.macrumors.com/",
        "https://9to5mac.com/",
        "https://www.androidauthority.com/",
        "https://www.windowscentral.com/",
        "https://www.neowin.net/",
        "https://www.datacenterdynamics.com/en/news/",
        "https://blocksandfiles.com/",
        "https://www.storagenewsletter.com/",
        "https://www.semianalysis.com/",
        "https://www.eetimes.com/",
        "https://semiengineering.com/",
        "https://www.informationweek.com/",
        "https://www.computerworld.com/",
        "https://www.infoworld.com/",
        "https://www.crn.com/news",
        "https://www.cio.com/",
        "https://www.techrepublic.com/",
        "https://www.utilitydive.com/",
        "https://www.renewableenergyworld.com/",
        "https://www.pv-magazine.com/",
        "https://electrek.co/",
        "https://cleantechnica.com/",
        "https://www.energy-storage.news/",
        "https://www.offshore-energy.biz/",
        "https://www.offshore-mag.com/",
        "https://www.powermag.com/",
        "https://www.power-technology.com/",
        "https://www.worldoil.com/",
        "https://www.autonews.com/",
        "https://www.automotiveworld.com/news-releases/",
        "https://www.wardsauto.com/",
        "https://www.carscoops.com/",
        "https://www.motor1.com/news/",
        "https://insideevs.com/news/",
        "https://www.teslarati.com/",
        "https://www.flightglobal.com/",
        "https://aviationweek.com/",
        "https://simpleflying.com/",
        "https://www.airwaysmag.com/",
        "https://breakingdefense.com/",
        "https://www.defensenews.com/",
        "https://www.janes.com/osint-insights/defence-news",
        "https://www.space.com/news",
        "https://spacenews.com/",
        "https://www.nasaspaceflight.com/",
        "https://www.statnews.com/",
        "https://www.fiercepharma.com/",
        "https://www.fiercebiotech.com/",
        "https://www.biopharmadive.com/",
        "https://www.biospace.com/news/",
        "https://endpts.com/",
        "https://www.pharmalive.com/",
        "https://medcitynews.com/",
        "https://www.mmm-online.com/",
        "https://www.healthcareitnews.com/",
        "https://www.modernhealthcare.com/",
        "https://www.retaildive.com/",
        "https://www.retailwire.com/",
        "https://www.modernretail.co/",
        "https://www.grocerydive.com/",
        "https://www.restaurantbusinessonline.com/",
        "https://www.qsrmagazine.com/",
        "https://www.fooddive.com/",
        "https://footwearnews.com/",
        "https://ww.fashionnetwork.com/",
        "https://www.glossy.co/",
        "https://www.adweek.com/",
        "https://adage.com/",
        "https://digiday.com/",
        "https://deadline.com/",
        "https://variety.com/",
        "https://www.hollywoodreporter.com/",
        "https://www.freightwaves.com/",
        "https://www.supplychaindive.com/",
        "https://www.joc.com/",
        "https://splash247.com/",
        "https://www.tradewindsnews.com/",
        "https://www.maritime-executive.com/",
        "https://gcaptain.com/",
        "https://www.railwaygazette.com/",
        "https://www.miningweekly.com/",
        "https://www.mining-journal.com/",
        "https://www.steelorbis.com/steel-news/latest-news/",
        "https://www.fastmarkets.com/insights/",
        "https://www.recyclingtoday.com/",
        "https://therealdeal.com/",
        "https://www.constructiondive.com/",
        "https://www.enr.com/",
        "https://www.lightreading.com/",
        "https://www.fierce-network.com/",
        "https://www.rcrwireless.com/",
        "https://www.telecoms.com/",
        "https://www.bleepingcomputer.com/",
        "https://therecord.media/",
        "https://www.securityweek.com/",
        "https://www.darkreading.com/",
        "https://krebsonsecurity.com/",
    ],
    "corporate_newsrooms": [
        "https://www.apple.com/newsroom/",
        "https://news.microsoft.com/",
        "https://blog.google/inside-google/company-announcements/",
        "https://www.aboutamazon.com/news",
        "https://nvidianews.nvidia.com/",
        "https://about.fb.com/news/",
        "https://www.tesla.com/blog",
        "https://www.broadcom.com/company/news",
        "https://pr.tsmc.com/english/news",
        "https://news.samsung.com/global/",
        "https://www.asml.com/en/news/press-releases",
        "https://www.amd.com/en/newsroom.html",
        "https://newsroom.intel.com/",
        "https://www.qualcomm.com/news/releases",
        "https://newsroom.arm.com/",
        "https://newsroom.ibm.com/",
        "https://www.oracle.com/news/",
        "https://www.salesforce.com/news/",
        "https://news.adobe.com/",
        "https://newsroom.cisco.com/",
        "https://news.sap.com/",
        "https://www.sony.com/en/SonyInfo/News/Press/",
        "https://www.dell.com/en-us/dt/corporate/newsroom.htm",
        "https://www.hp.com/us-en/newsroom.html",
        "https://www.jpmorganchase.com/ir/news",
        "https://newsroom.bankofamerica.com/",
        "https://www.citigroup.com/global/news",
        "https://newsroom.wf.com/",
        "https://www.goldmansachs.com/pressroom/",
        "https://www.morganstanley.com/press-releases",
        "https://www.blackrock.com/corporate/newsroom",
        "https://corporate.vanguard.com/content/corporatesite/us/en/corp/articles.html",
        "https://www.jnj.com/media-center/press-releases",
        "https://www.unitedhealthgroup.com/newsroom.html",
        "https://www.lilly.com/news",
        "https://www.novonordisk.com/news-and-media/news-and-ir-materials.html",
        "https://www.merck.com/news/",
        "https://www.pfizer.com/news",
        "https://news.abbvie.com/",
        "https://www.astrazeneca.com/media-centre.html",
        "https://www.roche.com/media/releases",
        "https://www.novartis.com/news",
        "https://corporate.walmart.com/news",
        "https://www.coca-colacompany.com/media-center",
        "https://www.pepsico.com/our-stories/press-release",
        "https://us.pg.com/newsroom/",
        "https://about.nike.com/en/newsroom",
        "https://corporate.mcdonalds.com/corpmcd/our-stories.html",
        "https://about.starbucks.com/stories/",
        "https://thewaltdisneycompany.com/news/",
        "https://about.netflix.com/en/newsroom",
        "https://corporate.exxonmobil.com/news",
        "https://www.chevron.com/newsroom",
        "https://www.shell.com/news-and-insights/newsroom.html",
        "https://www.bp.com/en/global/corporate/news-and-insights.html",
        "https://totalenergies.com/media/news",
        "https://www.aramco.com/en/news-media/news",
        "https://www.equinor.com/news",
        "https://www.rwe.com/en/press/rwe-ag/",
        "https://www.enel.com/media/explore/search-press-releases",
        "https://www.geaerospace.com/news",
        "https://www.caterpillar.com/en/news/caterpillarNews.html",
        "https://www.deere.com/en/news/",
        "https://press.siemens.com/global/en",
        "https://www.honeywell.com/us/en/press",
        "https://boeing.mediaroom.com/",
        "https://www.airbus.com/en/newsroom",
        "https://news.lockheedmartin.com/",
        "https://www.rtx.com/news",
        "https://global.toyota/en/newsroom/",
        "https://group.mercedes-benz.com/company/news/",
        "https://www.press.bmwgroup.com/global",
        "https://www.volkswagen-group.com/en/press-releases-18165",
        "https://media.ford.com/content/fordmedia/fna/us/en/news.html",
        "https://news.gm.com/",
        "https://www.stellantis.com/en/news/press-releases",
        "https://usa.visa.com/about-visa/newsroom.html",
        "https://www.mastercard.com/news/",
        "https://newsroom.paypal-corp.com/",
        "https://block.xyz/inside",
        "https://press.aboutamazon.com/",
        "https://newsroom.spotify.com/",
        "https://news.airbnb.com/",
        "https://investor.uber.com/news-events/news/press-release-details/default.aspx",
        "https://www.doordash.com/news/",
        "https://newsroom.booking.com/",
        "https://www.expediagroup.com/newsroom/",
        "https://newsroom.snap.com/",
        "https://newsroom.pinterest.com/",
        "https://newsroom.tiktok.com/",
        "https://news.linkedin.com/",
        "https://investor.atmeta.com/press-releases/",
        "https://investor.costco.com/news/default.aspx",
        "https://corporate.target.com/press/releases",
        "https://corporate.homedepot.com/newsroom",
        "https://corporate.lowes.com/newsroom",
        "https://newsroom.fedex.com/",
        "https://about.ups.com/us/en/newsroom.html",
        "https://www.maersk.com/news/",
        "https://www.dhl.com/global-en/home/press/press-archive.html",
        "https://www.basf.com/global/en/media/news-releases",
        "https://www.bayer.com/en/news-stories",
        "https://www.3m.com/3M/en_US/company-us/news-center/",
        "https://www.dow.com/en-us/news.html",
        "https://corporate.evonik.com/en/media/press-releases",
        "https://www.abb.com/news",
        "https://www.se.com/ww/en/about-us/newsroom/news/press-releases/",
        "https://www.philips.com/a-w/about/news/archive/standard/about/news/press.html",
        "https://www.unilever.com/news/press-and-media/press-releases/",
        "https://www.nestle.com/media/news",
        "https://www.loreal.com/en/press-releases/",
    ],
}


CATEGORY_PRIORITY = {
    "official_macro_regulation": 100,
    "exchanges_market_infra": 95,
    "corporate_newsrooms": 90,
    "global_finance": 85,
    "markets_investing": 80,
    "crypto_blockchain": 75,
    "sector_trade": 70,
}


def build_catalog() -> list[SourceSeed]:
    seen: set[str] = set()
    result: list[SourceSeed] = []
    for category, urls in GROUPS.items():
        for url in urls:
            host = (urlparse(url).hostname or "").lower().removeprefix("www.")
            if not host or host in seen:
                continue
            seen.add(host)
            result.append(SourceSeed(url=url, category=category, priority=CATEGORY_PRIORITY[category]))
    result.sort(key=lambda item: (-item.priority, item.domain))
    # Keep the packaged direct-source catalog inside the HADES 300..500 contract.
    return result[:480]


CATALOG = build_catalog()

# Guardrails required by the plugin contract.
assert 300 <= len(CATALOG) <= 500, f"catalog must contain 300..500 unique websites, got {len(CATALOG)}"
assert all("google.com/news" not in s.url and "news.google" not in s.url for s in CATALOG)
